version: 0.2
phases:
  build:
    commands:
      # - apt-get update
      # - apt-get install -y jq
      # - sh scripts/start-schema.sh
      - sh scripts/udpate-request-mapping-template.sh
      # - sh scripts/update-respone-mapping-template.sh
