version: 0.2

env:
  variables:
    API_ID: "hpxw6qg7d5crjlsbpm6ge6x6au"
    GITHUB_REPO_URL: "https://raw.githubusercontent.com/MrinalBhoumick/appsync/main/templates/data.graphql"
    API_NAME: "AppSyncCommercial"

phases:
  pre_build:
    commands:
      - echo "Starting schema creation for AppSync API"
      - curl -o schema.graphql $GITHUB_REPO_URL

  build:
    commands:
      - SCHEMA_DEFINITION=$(< schema.graphql)
      - aws appsync update-graphql-api --api-id $API_ID --definition "$SCHEMA_DEFINITION" --name "$API_NAME"

  post_build:
    commands:
      - echo "Schema update initiated successfully"
