version: 0.2
phases:
  install:
    commands:
      - apt-get update

  pre_build:
    commands:
      - echo "Install AWS CLI and configure credentials..."
      - apt-get install -y awscli
  build:
    commands:
      - echo "Starting schema update for AppSync API..."
      - bash scripts/update-schema.sh
      - sh scripts/update-request-mapping-template.sh
      - sh scripts/update-response-mapping-template.sh
