version: 0.2

env:
  variables:
    API_ID: "baqk365bi5hjbdogcptccb6ytq"
    GITHUB_REPO_URL: "https://github.com/MrinalBhoumick/appsync.git"
    API_NAME: "commercial_module_prod"
    AUTHENTICATION_TYPE: "AWS_LAMBDA"
    API_URL: "https://acgdakvy7bdpphsb4h2r3h2ita.appsync-api.ap-south-1.amazonaws.com/graphql"

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - pip install boto3 requests
      - pip install requests-aws4auth
      - apt-get update && apt-get install -y jq

  pre_build:
    commands:
      # Assuming role
      - ROLE_ARN="arn:aws:iam::058264356572:role/sts-appsync-role"
      - CREDENTIALS=$(aws sts assume-role --role-arn $ROLE_ARN --role-session-name codebuild-session)
      - export AWS_ACCESS_KEY_ID=$(echo $CREDENTIALS | jq -r '.Credentials.AccessKeyId')
      - export AWS_SECRET_ACCESS_KEY=$(echo $CREDENTIALS | jq -r '.Credentials.SecretAccessKey')
      - export AWS_SESSION_TOKEN=$(echo $CREDENTIALS | jq -r '.Credentials.SessionToken')

      # Configure Git to fetch the code from GitHub
      - git clone $GITHUB_REPO_URL repo
      - cd repo

  build:
    commands:
      - python update_appsync.py

artifacts:
  files:
    - "**/*"
