version: 0.2

phases:
  install:
    commands:
      - apt-get update
      - apt-get install -y jq

  pre_build:
    commands:
      - echo "Setting up AWS credentials"

  build:
    commands:
      - echo "Starting schema update for AppSync API"
      - bash scripts/update-schema.sh
      - sh scripts/update-request-mapping-template.sh
      - sh scripts/update-response-mapping-template.sh

  post_build:
    commands:
      - echo "Build process completed"
