version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - echo "Install phase commands go here"
  pre_build:
    commands:
      - echo "Starting schema creation for AppSync API"
  build:
    commands:
      - aws appsync start-schema-creation --api-id <your-api-id> --definition file://templates/data.graphql
  post_build:
    commands:
      - echo "Schema creation initiated successfully"
