version: 0.2

phases:
  install:
    commands:
      - apt-get update

  pre_build:
    commands:
      - echo "Install AWS CLI and configure credentials..."
      - apt-get install -y awscli
      - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
      - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
  build:
    commands:
      - echo "Starting schema update for AppSync API..."
      - bash scripts/update-schema.sh
      - sh scripts/update-request-mapping-template.sh
      - sh scripts/update-response-mapping-template.sh
