version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - pip install boto3 requests requests-aws4auth graphql
      - apt-get update && apt-get install -y jq

  build:
    commands:
      - python update_appsync.py
