version: 0.2

phases:
  install:
    commands:
      - apt-get update

  build:
    commands:
      - bash scripts/update-schema.sh
      - sh scripts/update-request-mapping-template.sh
      - sh scripts/update-response-mapping-template.sh
