name: Update AppSync Schema

on:
  push:
    branches:
      - main

jobs:
  update-schema:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::058264356572:role/sts-appsync-role
          aws-region: ap-south-1
          role-session-name: GitHubActions

      - name: Download AWS CLI v2
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"

      - name: Install unzip
        run: |
          sudo apt-get update
          sudo apt-get install unzip -y

      - name: Unzip AWS CLI v2
        run: |
          unzip awscliv2.zip
          
      - name: Install AWS CLI
        run: |
          sudo ./aws/install -i /usr/local/aws-cli -b /usr/local/bin --update

      - name: Base64 encode GraphQL schema
        run: |
          base64 -w 0 templates/data.graphql > $GITHUB_WORKSPACE/data.graphql.base64
        env:
          GITHUB_WORKSPACE: ${{ github.workspace }}

      - name: Verify file content
        run: |
          cat $GITHUB_WORKSPACE/data.graphql.base64

      - name: Update AppSync Schema
        id: update-schema
        run: |
          result=$(aws appsync start-schema-creation --api-id 6o2znoypyjdthf6vdtf6rhwnz4 --definition fileb://$GITHUB_WORKSPACE/data.graphql.base64)
          echo "::set-output name=status::$(echo $result | jq -r '.status')"

      - name: Wait for schema creation to complete
        run: |
          status=""
          while [[ "$status" != "SUCCESS" && "$status" != "FAILED" ]]; do
            sleep 10
            status=$(aws appsync get-schema-creation-status --api-id 6o2znoypyjdthf6vdtf6rhwnz4 | jq -r '.status')
            echo "Current status: $status"
          done
          echo "Schema creation status: $status"

      - name: Check schema creation result
        run: |
          if [[ "$status" == "SUCCESS" ]]; then
            echo "Schema creation completed successfully."
          else
            echo "Schema creation failed or timed out."
            exit 1
          fi

      - name: Update request mapping template
        run: |
          chmod +x scripts/update-request-mapping-template.sh
          aws appsync update-function --api-id 6o2znoypyjdthf6vdtf6rhwnz4 --name requestMappingTemplate --function-version "2017-02-28" --request-mapping-template fileb://scripts/update-request-mapping-template.sh

      - name: Update response mapping template
        run: |
          aws appsync update-function --api-id 6o2znoypyjdthf6vdtf6rhwnz4 --name responseMappingTemplate --function-version "2017-02-28" --response-mapping-template file://scripts/update-response-mapping-template.sh
