name: Deploy AppSync Schema

on:
  push:
    branches:
      - main

jobs:
  deploy-schema:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::058264356572:role/sts-appsync-role
          aws-region: ap-south-1
          role-session-name: GitHubActions

      - name: Install Python and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install python3-pip -y
          pip3 install boto3 jq

      - name: Base64 encode GraphQL schema
        run: |
          base64 -w 0 $GITHUB_WORKSPACE/templates/data.graphql > $GITHUB_WORKSPACE/data.graphql.base64

      - name: Make start-schema.sh executable
        run: chmod +x $GITHUB_WORKSPACE/scripts/start-schema.sh

      - name: Deploy AppSync Schema
        run: $GITHUB_WORKSPACE/scripts/start-schema.sh
        env:
          API_ID: 6o2znoypyjdthf6vdtf6rhwnz4
          API_NAME: "AppSync-Commercial"  
          AUTHENTICATION_TYPE: "API_KEY"  
          GITHUB_REPO_URL: "https://raw.githubusercontent.com/MrinalBhoumick/appsync/main/templates/data.graphql"
